version: '3.8'

services:
  ocr-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ocr-text-detection-llm
    image: ocr-text-detection:latest
    ports:
      - "5678:5678"
    environment:
      # Server settings
      - PORT=5678
      - HOST=0.0.0.0
      
      # OCR settings
      - USE_GPU_AUTO=true
      - FORCE_CPU=false
      - FORCE_GPU=false
      
      # LLM Correction settings
      - LLM_CORRECTION_ENABLED=true
      - LLM_PROVIDER=groq
      - LLM_MODEL=
      - LLM_TIMEOUT=30
      
      # API Keys (QUAN TRỌNG: Thay bằng API key thật của bạn)
      - GROQ_API_KEY=${GROQ_API_KEY:-your_groq_api_key_here}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your_openai_api_key_here}
      
      # File cleanup
      - CLEANUP_AFTER_SECONDS=600
    
    volumes:
      # Mount volumes để persist data (optional)
      - ./uploads:/app/uploads
      - ./output:/app/output
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5678/ocr/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Resource limits (optional, điều chỉnh theo nhu cầu)
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G
